# Server configurations
target:
  region: "us-east-1"
  id: "329914591859"

# Email notifications
email:
  recv: "aseemsethi@yahoo.com"
  sender: "aseemsethi@yahoo.com"
  subject: "TcTool Test Results"

# Enumerate Test Cases that need to be run
tests:
  - "cis"
  - "inspector"
  - "config"
  - "securityHub"