# Server configurations
target:
  region: "us-east-1"
  id: "329914591859"

# Email notifications
email:
  id: "aseemsethi@yahoo.com"

# Database credentials
database:
  user: "admin"
  pass: "super-pedro-1980"