# Server configurations
target:
  region: "us-east-1"
  id: "329914591859"

# Email notifications
email:
  recv: "aseemsethi@yahoo.com"
  sender: "aseemsethi@yahoo.com"
  subject: "TcTool Test Results"

# Database credentials
database:
  user: "admin"
  pass: "super-pedro-1980"